title: Code Blog
author: Byron Saltos
email: bantoniosaltos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre programacion, software y demas.
# social links
twitter_username: https://twitter.com/BakuzByron
github_username:  https://github.com/bakuz

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
